# Generated by Django 4.2.16 on 2025-02-15 22:13

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='capacidade_maxima',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Número máximo de participantes + alunos permitidos na atividade',
                verbose_name='Capacidade Máxima',
            ),
        ),
    ]
