# Generated by Django 4.2.16 on 2025-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0002_add_capacidade_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='capacidade_maxima',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de pessoas na atividade', verbose_name='Capacidade Máxima'),
        ),
    ]
