# Generated by Django 4.2.16 on 2025-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0003_alter_atividade_capacidade_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(verbose_name='Horario')),
                ('inscricao', models.ForeignKey(null=True, blank=True, to='projetoApp.inscricao', on_delete=models.CASCADE)),
                ('aluno', models.ForeignKey(null=True, blank=True, to='projetoApp.aluno', on_delete=models.CASCADE)),
                ('atividade', models.ForeignKey(null=True, blank=True, to='projetoApp.atividade', on_delete=models.CASCADE)),
            ],
        ),
    ]