# Generated by Django 4.2.16 on 2025-02-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0006_remove_participante_instituicao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convite',
        ),
    ]
